---
- name: Interactive Traefik Setup
  hosts: localhost
  gather_facts: no
  
  vars_prompt:
    - name: cloudflare_dns_api_token
      prompt: "Cloudflare DNS API Token"
      private: yes
      
    - name: docker_network
      prompt: "Docker Network"
      default: "traefik"
      
    - name: enable_ipv6
      prompt: "Enable IPv6? (true/false)"
      default: "false"
      
    - name: traefik_dashboard
      prompt: "Traefik Dashboard URL"
      
    - name: traefik_ipv4
      prompt: "IPv4 Address"
      default: "0.0.0.0"
      
    - name: traefik_ipv6
      prompt: "IPv6 Address"
      default: "::"
      
    - name: traefik_email
      prompt: "Email for Let's Encrypt"

  vars:
    traefik:
      version: "v3.3"
      collect_anonymous_stats: true
      certresolver: "letsencrypt-dns-cloudflare"
      ipv4: "{{ traefik_ipv4 }}"
      ipv6: "{{ traefik_ipv6 }}"
      dashboard: "{{ traefik_dashboard }}"
      email: "{{ traefik_email }}"

  tasks:
    - name: Process templates
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: ".env.j2", dest: "./traefik/.env" }
        - { src: "docker-compose.yml.j2", dest: "./traefik/docker-compose.yml" }
        - { src: "config/dynamic.yml.j2", dest: "./traefik/config/dynamic.yml" }
        - { src: "config/traefik.yml.j2", dest: "./traefik/config/traefik.yml" }